<a href="https://colab.research.google.com/github/shreeshreeya69-crypto/simple-linear-regression-ybi/blob/main/Simple_Linear_Regression_YBI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This project focuses on predicting sales using Simple Linear Regression

The project analyzes the relationship between an independent variable
and a dependent variable and uses a linear regression model to make predictions.

YBI Foundation

Business and Data Analyst

Machine Learning/Regression

Project Objectives:-

1. Understand the concept of Simple Linear
Regression.
2. Load and explore the dataset.
3. Perform basic data cleaning.
4. Analyze the relationship between variables.
5. Visualize the data.
6. Train a Simple Linear Regression model.
7. Make predictions using the trained model.
8. Evaluate the performance of the model.
9. Generate useful business insights.

Problem:-

Businesses often want to understand how one factor affects their sales.

In this project, Simple Linear Regression will be used to study the
relationship between advertising expenditure and sales.

The model will then be used to predict sales based on advertising expenditure.

Simple Linear Regression is a supervised machine learning algorithm
used to study the relationship between one independent variable and
one dependent variable.

The model fits a straight line through the data and uses this line
to make predictions.

Variable Types

- Independent Variable (X): Advertising Expenditure
- Dependent Variable (Y): Sales

In [1]:
print("Sales Prediction Using Simple Linear Regression")
print("YBI Foundation Internship")

Sales Prediction Using Simple Linear Regression
YBI Foundation Internship

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

- Python
- Google Colab
- Pandas
- NumPy
- Matplotlib
- GitHub

Day 1 Progress

Completed Tasks

- Created the project notebook.
- Defined the project title.
- Added project objectives.
- Defined the business problem.
- Studied the basic concept of Simple Linear Regression.
- Imported basic Python libraries.
- Created the initial project structure.

Day 2 - Dataset Selection and Understanding



Dataset Selection

For this project, the Advertising dataset is selected to study
the relationship between advertising expenditure and sales.

The dataset contains information about advertising expenditure
through different media and the corresponding sales.

For Simple Linear Regression, TV advertising expenditure will be
used as the independent variable and Sales will be used as the
dependent variable.

In [3]:
import pandas as pd

url = "https://raw.githubusercontent.com/selva86/datasets/master/Advertising.csv"

df = pd.read_csv(url)

df.head()

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [4]:
df.columns

Index(['Unnamed: 0', 'TV', 'radio', 'newspaper', 'sales'], dtype='object')

In [5]:
df.shape

(200, 5)

## Dataset Variables

### TV
Amount spent on TV advertising.

### Radio
Amount spent on Radio advertising.

### Newspaper
Amount spent on Newspaper advertising.

### Sales
Sales generated from the advertising expenditure.

### Variables Used in This Project

Independent Variable (X):
TV advertising expenditure

Dependent Variable (Y):
Sales

In [20]:
df.head(10)

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9
5           6    8.7   48.9       75.0    7.2
6           7   57.5   32.8       23.5   11.8
7           8  120.2   19.6       11.6   13.2
8           9    8.6    2.1        1.0    4.8
9          10  199.8    2.6       21.2   10.6

In [21]:
df.tail()

     Unnamed: 0     TV  radio  newspaper  sales
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  200 non-null    int64
 1   TV          200 non-null    float64
 2   radio       200 non-null    float64
 3   newspaper   200 non-null    float64
 4   sales       200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB

In [23]:
df.describe()

       Unnamed: 0          TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [24]:
X = df[["TV"]]
y = df["sales"]

In [25]:
print("Independent Variable (X): TV")
print("Dependent Variable (y): sales")

Independent Variable (X): TV
Dependent Variable (y): sales

In [26]:
print(X.head())

      TV
0  230.1
1   44.5
2   17.2
3  151.5
4  180.8

In [27]:
print(y.head())

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: sales, dtype: float64

Day 2 — Dataset Observations



The following observations were made after examining the dataset:

1. The dataset contains information about advertising expenditure and sales.
2. TV, Radio and Newspaper are advertising-related variables.
3. Sales is the target variable.
4. TV advertising expenditure is selected as the independent variable.
5. Sales is selected as the dependent variable.
6. The dataset contains numerical values suitable for regression analysis.
7. Simple Linear Regression will be used to study the relationship between TV advertising expenditure and Sales.

In [34]:
df.to_csv("Advertising.csv",index=False)

In [35]:
from google.colab import files
files.download("Advertising.csv")